//! FDN-992 regression: tiling patterns using the iText "paint the tile once,
//! never repeat" idiom (/XStep 99999 /YStep 99999 on a page-sized cell) made
//! hayro size the tile pixmap from the scaled step — the f32→u16 cast
//! saturated at 65535 and allocated a 65535×65535×4 ≈ 16 GiB pixmap. The fix
//! decouples the cell bitmap from the step on oversized axes: the pixmap
//! stores one padded cell and the paint transform places the single lattice
//! instance that can intersect the painted area.
//!
//! The fixture (tests/fixtures/tiling-step-overflow.pdf, generated by
//! scripts/make_tiling_fixture.py) has a deliberately non-uniform cell so the
//! two failure modes of naive fixes stay detectable: a clamped period would
//! repeat cell content early (ghosts), a downscaled cell would blur the
//! hairline away. Pages 1–3 are pixel-identical to MuPDF at 144 dpi.
//!
//! The allocation-size guard lives in tests/tiling_pattern_alloc.rs (its own
//! binary: it needs a counting global allocator).

#![cfg(feature = "render")]

use std::path::{Path, PathBuf};

use hayro::{
    hayro_interpret::InterpreterSettings, hayro_syntax::Pdf, vello_cpu::color::palette::css::WHITE,
    RenderCache, RenderSettings,
};

const DPI_144_SCALE: f32 = 144.0 / 72.0;
const PAGE_HEIGHT_PT: f32 = 842.0;

/// Whether these tests are running against an unpacked crates.io release
/// rather than a checkout of the repository (same convention as
/// tests/text.rs). It matters here because cargo drops both the
/// `[patch.crates-io]` table and `vendor/` when packaging, so the published
/// crate builds against the unpatched hayro — where every test below would
/// re-trigger the FDN-992 ~16 GiB allocation instead of merely failing.
/// `hayro` is deliberately NOT in .github/publish-patch-allowlist.txt: the
/// release gate blocks publishing until the fix ships upstream.
fn is_packaged_crate() -> bool {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("Cargo.toml.orig")
        .exists()
}

/// Explicit, loud skip for the packaged crate; a normal git checkout never
/// takes this path.
macro_rules! skip_on_packaged_crate {
    () => {
        if is_packaged_crate() {
            eprintln!("skipping: the published crate builds without the vendored hayro fix");
            return;
        }
    };
}

fn fixture() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("tiling-step-overflow.pdf")
}

fn render_page(page_index: usize, scale: f32) -> (Vec<u8>, u16, u16) {
    let data = std::fs::read(fixture()).unwrap();
    let pdf = Pdf::new(data).unwrap();
    let pages = pdf.pages();
    let settings = InterpreterSettings::default();
    let render_settings = RenderSettings {
        x_scale: scale,
        y_scale: scale,
        bg_color: WHITE,
        ..Default::default()
    };
    let cache = RenderCache::new();
    let pixmap = hayro::render(&pages[page_index], &cache, &settings, &render_settings);
    let (width, height) = (pixmap.width(), pixmap.height());
    (pixmap.data_as_u8_slice().to_vec(), width, height)
}

/// Sample the rendered RGBA at a pattern-space point (PDF points, y-up).
fn sample(data: &[u8], width: u16, x_pt: f32, y_pt: f32, scale: f32) -> [u8; 4] {
    let col = (x_pt * scale).round() as usize;
    let row = ((PAGE_HEIGHT_PT - y_pt) * scale).round() as usize;
    let idx = (row * usize::from(width) + col) * 4;
    data[idx..idx + 4].try_into().unwrap()
}

fn assert_rgb(actual: [u8; 4], expected: [u8; 3], what: &str) {
    let close = actual[0].abs_diff(expected[0]) <= 2
        && actual[1].abs_diff(expected[1]) <= 2
        && actual[2].abs_diff(expected[2]) <= 2;
    assert!(close, "{what}: got {actual:?}, expected ~{expected:?}");
}

fn assert_same_pixels(a: &[u8], b: &[u8], what: &str) {
    assert_eq!(a.len(), b.len(), "{what}: buffer sizes differ");
    let worst = a
        .iter()
        .zip(b)
        .map(|(x, y)| x.abs_diff(*y))
        .max()
        .unwrap_or(0);
    assert!(worst <= 2, "{what}: pixel channels differ by up to {worst}");
}

#[test]
fn huge_step_pattern_renders_cell_content() {
    skip_on_packaged_crate!();
    let (data, width, height) = render_page(0, DPI_144_SCALE);
    assert_eq!((width, height), (1190, 1684));

    let s = DPI_144_SCALE;
    assert_rgb(
        sample(&data, width, 150.0, 700.0, s),
        [255, 0, 0],
        "red quadrant",
    );
    assert_rgb(
        sample(&data, width, 450.0, 200.0, s),
        [0, 153, 0],
        "green quadrant",
    );
    assert_rgb(
        sample(&data, width, 425.0, 625.0, s),
        [0, 0, 255],
        "blue mark",
    );
    assert_rgb(sample(&data, width, 100.7, 300.0, s), [0, 0, 0], "hairline");
    assert_rgb(
        sample(&data, width, 500.0, 700.0, s),
        [255, 255, 255],
        "empty top-right",
    );
    assert_rgb(
        sample(&data, width, 150.0, 100.0, s),
        [255, 255, 255],
        "empty bottom-left",
    );
}

#[test]
fn phase_shifted_pattern_matches_baseline() {
    skip_on_packaged_crate!();
    // Page 2 translates the pattern by (-99999, -99999): the page sits on
    // lattice instance (1, 1) instead of (0, 0). Placement must follow the
    // lattice, so the output is identical to page 1.
    let (base, ..) = render_page(0, DPI_144_SCALE);
    let (shifted, ..) = render_page(1, DPI_144_SCALE);
    assert_same_pixels(&base, &shifted, "instance (1,1) placement");
}

#[test]
fn gap_window_renders_blank() {
    skip_on_packaged_crate!();
    // Page 3 translates the pattern by (-50000, 0): the page falls in the gap
    // between instance 0 and instance 1, where nothing may be painted.
    let (data, ..) = render_page(2, DPI_144_SCALE);
    let painted = data
        .chunks_exact(4)
        .any(|px| px[0] < 250 || px[1] < 250 || px[2] < 250);
    assert!(!painted, "gap window painted pattern content");
}

#[test]
fn negative_steps_match_baseline() {
    skip_on_packaged_crate!();
    // Page 4 uses XStep/YStep -99999: the lattice {k·step} is the same set as
    // page 1's, and hayro's convention (unlike MuPDF, which renders nothing
    // for negative steps) is to paint it. This pins internal consistency with
    // the small-step legacy path, which also paints negative-step patterns.
    let (base, ..) = render_page(0, DPI_144_SCALE);
    let (negative, ..) = render_page(3, DPI_144_SCALE);
    assert_same_pixels(&base, &negative, "negative-step lattice");
}

#[test]
fn oversized_viewport_has_no_ghost_repetition() {
    skip_on_packaged_crate!();
    // At 400 dpi the page raster is 3305×4677 px — beyond hayro's 3000 px
    // MAX_PIXMAP_SIZE in both axes. A fix that merely clamped the period
    // pixmap to 3000 px would tile the cell content again past device
    // x/y = 3000 (e.g. the red quadrant would reappear in the blank
    // bottom-left region). The single-cell placement must not repeat.
    let scale = 400.0 / 72.0;
    let (data, width, height) = render_page(0, scale);
    assert_eq!((width, height), (3305, 4677));

    // True blanks whose device coordinates sit past the 3000 px boundary in
    // y (150,100 → row ≈ 4122) and x (560,500 → col ≈ 3111).
    assert_rgb(
        sample(&data, width, 150.0, 100.0, scale),
        [255, 255, 255],
        "bottom-left stays blank",
    );
    assert_rgb(
        sample(&data, width, 560.0, 500.0, scale),
        [255, 255, 255],
        "right edge stays blank",
    );
    // Real content still lands where it should, full resolution.
    assert_rgb(
        sample(&data, width, 150.0, 700.0, scale),
        [255, 0, 0],
        "red quadrant",
    );
    assert_rgb(
        sample(&data, width, 450.0, 200.0, scale),
        [0, 153, 0],
        "green quadrant",
    );
    assert_rgb(
        sample(&data, width, 100.7, 300.0, scale),
        [0, 0, 0],
        "hairline stays sharp",
    );
}

#[test]
fn mixed_axes_pad_x_repeat_y() {
    skip_on_packaged_crate!();
    // Page 5 mixes the per-axis decisions: XStep 99999 on a 300 pt-wide cell
    // (oversized → single cell, Extend::Pad) with YStep 100 on a 100 pt-tall
    // cell (normal → legacy step pixmap, Extend::Repeat). The result is a
    // stack of teal/orange bands with a hairline at y = 49 + 100k, repeating
    // up the whole page, while everything right of x = 300 stays blank —
    // repetition on y proves Repeat survived, the blank right side proves Pad
    // pads with transparency. Matches MuPDF within 1/255 at 144 dpi.
    let (data, width, height) = render_page(4, DPI_144_SCALE);
    assert_eq!((width, height), (1190, 1684));

    let s = DPI_144_SCALE;
    // Mid-band samples (y = 25/75 + 100k avoids the hairline at [49, 50.5]).
    assert_rgb(
        sample(&data, width, 75.0, 25.0, s),
        [0, 128, 128],
        "teal, band 0",
    );
    assert_rgb(
        sample(&data, width, 75.0, 425.0, s),
        [0, 128, 128],
        "teal, band 4",
    );
    assert_rgb(
        sample(&data, width, 225.0, 75.0, s),
        [255, 128, 0],
        "orange, band 0",
    );
    assert_rgb(
        sample(&data, width, 225.0, 725.0, s),
        [255, 128, 0],
        "orange, band 7",
    );
    assert_rgb(
        sample(&data, width, 100.0, 49.75, s),
        [0, 0, 0],
        "hairline, band 0",
    );
    assert_rgb(
        sample(&data, width, 100.0, 449.75, s),
        [0, 0, 0],
        "hairline, band 4",
    );
    // Right of the 300 pt cell: the x axis must pad, never repeat.
    for y in [50.0, 421.0, 800.0] {
        assert_rgb(
            sample(&data, width, 450.0, y, s),
            [255, 255, 255],
            "pad region right of the cell",
        );
    }
}

#[test]
fn mixed_axes_phase_matches_baseline() {
    skip_on_packaged_crate!();
    // Page 6 is page 5 with /Matrix translate(-99999, 0): the visible window
    // sits on x lattice instance 1 while y keeps repeating — placement on the
    // padded axis must follow the lattice exactly as in the both-axes case.
    let (base, ..) = render_page(4, DPI_144_SCALE);
    let (shifted, ..) = render_page(5, DPI_144_SCALE);
    assert_same_pixels(&base, &shifted, "mixed-axes x instance 1 placement");
}
